import { runCommand } from "../primitives/runner.js";
import { createPullRequest, commentOnIssue } from "./github.js";
import type { GitHubIssue, StormConfig } from "./types.js";
import { log } from "./output.js";

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50);
}

export function branchName(issue: GitHubIssue): string {
  return `storm/issue-${issue.number}-${slugify(issue.title)}`;
}

export async function createBranch(
  name: string,
  cwd: string
): Promise<boolean> {
  // Try creating a new branch first
  const result = await runCommand(`git checkout -b "${name}"`, { cwd });
  if (result.exitCode === 0) return true;

  // Branch already exists — check it out and reset to current HEAD
  log.info(`Branch "${name}" already exists, resetting it`);
  const checkout = await runCommand(`git checkout "${name}"`, { cwd });
  if (checkout.exitCode !== 0) {
    log.error(`Failed to checkout branch: ${checkout.stderr}`);
    return false;
  }
  const reset = await runCommand(`git reset --hard "${name}@{upstream}" 2>/dev/null || git reset --hard HEAD`, { cwd });
  if (reset.exitCode !== 0) {
    log.warn(`Could not reset branch: ${reset.stderr}`);
  }
  return true;
}

export async function checkoutBase(
  baseBranch: string,
  cwd: string
): Promise<boolean> {
  const checkout = await runCommand(`git checkout "${baseBranch}"`, { cwd });
  if (checkout.exitCode !== 0) {
    log.error(`Failed to checkout ${baseBranch}: ${checkout.stderr}`);
    return false;
  }
  const pull = await runCommand("git pull", { cwd });
  if (pull.exitCode !== 0) {
    log.warn(`git pull failed: ${pull.stderr}`);
  }
  return true;
}

export async function commitAndPush(
  branch: string,
  issue: GitHubIssue,
  cwd: string
): Promise<boolean> {
  // Check for uncommitted changes
  const status = await runCommand("git status --porcelain", { cwd });
  if (!status.stdout.trim()) {
    log.info("No changes to commit");
    return true;
  }

  const addResult = await runCommand("git add -A", { cwd });
  if (addResult.exitCode !== 0) {
    log.error(`git add failed: ${addResult.stderr}`);
    return false;
  }

  const msg = `storm: implement #${issue.number} - ${issue.title}`;
  const commitResult = await runCommand(
    `git commit -m "${msg.replace(/"/g, '\\"')}"`,
    { cwd }
  );
  if (commitResult.exitCode !== 0) {
    log.error(`git commit failed: ${commitResult.stderr}`);
    return false;
  }

  const pushResult = await runCommand(
    `git push -u origin "${branch}"`,
    { cwd }
  );
  if (pushResult.exitCode !== 0) {
    log.error(`git push failed: ${pushResult.stderr}`);
    return false;
  }

  return true;
}

export async function openPR(
  config: StormConfig,
  issue: GitHubIssue,
  branch: string
): Promise<string | null> {
  try {
    const pr = await createPullRequest(config.github.repo, {
      title: `storm: #${issue.number} - ${issue.title}`,
      body: `Closes #${issue.number}\n\nAutomatically generated by storm-agent.`,
      head: branch,
      base: config.github.baseBranch,
    });

    await commentOnIssue(
      config.github.repo,
      issue.number,
      `Pull request created: ${pr.url}`
    );

    return pr.url;
  } catch (err) {
    log.error(`Failed to create PR: ${err}`);
    return null;
  }
}
