import { join } from "path";
import { runCommand, runCommandArgs } from "../primitives/runner.js";
import { createPullRequest, commentOnIssue } from "./github.js";
import type { GitHubIssue, StormConfig, AgentUsage } from "./types.js";
import { log, formatDuration } from "./output.js";
import { CONFIG_DIR, PR_DESCRIPTION_FILE } from "./constants.js";

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50);
}

export function branchName(issue: GitHubIssue): string {
  return `storm/issue-${issue.number}-${slugify(issue.title)}`;
}

export async function createBranch(
  name: string,
  cwd: string
): Promise<boolean> {
  // Try creating a new branch
  const result = await runCommandArgs(["git", "checkout", "-b", name], { cwd });
  if (result.exitCode === 0) return true;

  // Branch exists — delete it and recreate from current HEAD (base branch)
  log.info(`Branch "${name}" already exists, recreating from base`);
  const del = await runCommandArgs(["git", "branch", "-D", name], { cwd });
  if (del.exitCode !== 0) {
    log.error(`Failed to delete branch: ${del.stderr}`);
    return false;
  }
  const retry = await runCommandArgs(["git", "checkout", "-b", name], { cwd });
  if (retry.exitCode !== 0) {
    log.error(`Failed to create branch: ${retry.stderr}`);
    return false;
  }
  return true;
}

export async function checkoutBase(
  baseBranch: string,
  cwd: string
): Promise<boolean> {
  const checkout = await runCommandArgs(["git", "checkout", baseBranch], { cwd });
  if (checkout.exitCode !== 0) {
    log.error(`Failed to checkout ${baseBranch}: ${checkout.stderr}`);
    return false;
  }
  const pull = await runCommand("git pull", { cwd });
  if (pull.exitCode !== 0) {
    log.warn(`git pull failed: ${pull.stderr}`);
  }
  return true;
}

export async function commitAndPush(
  branch: string,
  issue: GitHubIssue,
  cwd: string
): Promise<boolean> {
  // Check for uncommitted changes
  const status = await runCommand("git status --porcelain", { cwd });
  if (!status.stdout.trim()) {
    log.info("No changes to commit");
    return true;
  }

  const addResult = await runCommand("git add -A", { cwd });
  if (addResult.exitCode !== 0) {
    log.error(`git add failed: ${addResult.stderr}`);
    return false;
  }

  const msg = `storm: implement #${issue.number} - ${issue.title}`;
  const commitResult = await runCommandArgs(["git", "commit", "-m", msg], { cwd });
  if (commitResult.exitCode !== 0) {
    log.error(`git commit failed: ${commitResult.stderr}`);
    return false;
  }

  const pushResult = await runCommandArgs(["git", "push", "-u", "origin", branch], { cwd });
  if (pushResult.exitCode !== 0) {
    log.error(`git push failed: ${pushResult.stderr}`);
    return false;
  }

  return true;
}

async function buildPRDescription(
  issue: GitHubIssue,
  branch: string,
  baseBranch: string,
  cwd: string
): Promise<string> {
  const templatePath = join(cwd, CONFIG_DIR, "pr", PR_DESCRIPTION_FILE);
  const templateFile = Bun.file(templatePath);

  let template: string;
  if (await templateFile.exists()) {
    template = await templateFile.text();
  } else {
    template = `Closes #{{ issue.number }}\n\n## Summary\n\n**{{ issue.title }}**\n\n{{ issue.body }}\n\n## Changes\n\n{{ changes.files }}\n\n{{ changes.summary }}\n\n## Considerations\n\n<!-- Describe the key design decisions, trade-offs, or constraints that shaped this implementation. -->\n\n## Test Plan\n\n<!-- Outline the steps taken or recommended to verify correctness. -->\n\n---\n\n_Automatically generated by [storm-agent](https://github.com/codebypanduro/storm-agent) on branch \`{{ branch }}\`._\n`;
  }

  // Gather git stats against the base branch
  const diffStat = await runCommandArgs(
    ["git", "diff", "--stat", `${baseBranch}...${branch}`],
    { cwd }
  );
  const changedFilesRaw = await runCommandArgs(
    ["git", "diff", "--name-only", `${baseBranch}...${branch}`],
    { cwd }
  );

  const fileList = changedFilesRaw.stdout
    .trim()
    .split("\n")
    .filter(Boolean)
    .map((f) => `- \`${f}\``)
    .join("\n");

  const summary = diffStat.stdout.trim().split("\n").pop()?.trim() ?? "";

  return template
    .replace(/\{\{\s*issue\.number\s*\}\}/g, String(issue.number))
    .replace(/\{\{\s*issue\.title\s*\}\}/g, issue.title)
    .replace(/\{\{\s*issue\.body\s*\}\}/g, issue.body)
    .replace(/\{\{\s*changes\.files\s*\}\}/g, fileList || "_No files changed._")
    .replace(/\{\{\s*changes\.summary\s*\}\}/g, summary ? `_${summary}_` : "")
    .replace(/\{\{\s*branch\s*\}\}/g, branch);
}

function formatPRComment(
  model: string,
  usage: AgentUsage,
  durationMs: number
): string {
  const totalTokens = usage.inputTokens + usage.outputTokens;
  const fmt = (n: number) => n.toLocaleString("en-US");

  return [
    "## Storm Agent Summary",
    "",
    `| | |`,
    `|---|---|`,
    `| **Model** | \`${model}\` |`,
    `| **Duration** | ${formatDuration(durationMs)} |`,
    `| **Total tokens** | ${fmt(totalTokens)} |`,
    `| **Input tokens** | ${fmt(usage.inputTokens)} |`,
    `| **Output tokens** | ${fmt(usage.outputTokens)} |`,
    ...(usage.cacheReadTokens > 0
      ? [`| **Cache read tokens** | ${fmt(usage.cacheReadTokens)} |`]
      : []),
    ...(usage.cacheCreationTokens > 0
      ? [`| **Cache creation tokens** | ${fmt(usage.cacheCreationTokens)} |`]
      : []),
  ].join("\n");
}

export async function openPR(
  config: StormConfig,
  issue: GitHubIssue,
  branch: string,
  cwd: string,
  stats?: { model: string; usage: AgentUsage; durationMs: number }
): Promise<string | null> {
  try {
    const body = await buildPRDescription(issue, branch, config.github.baseBranch, cwd);
    const pr = await createPullRequest(config.github.repo, {
      title: `storm: #${issue.number} - ${issue.title}`,
      body,
      head: branch,
      base: config.github.baseBranch,
    });

    await commentOnIssue(
      config.github.repo,
      issue.number,
      `Pull request created: ${pr.url}`
    );

    if (stats) {
      await commentOnIssue(
        config.github.repo,
        pr.number,
        formatPRComment(stats.model, stats.usage, stats.durationMs)
      );
    }

    return pr.url;
  } catch (err) {
    log.error(`Failed to create PR: ${err}`);
    return null;
  }
}
